### PR TITLE
Migrate to bootstrap

### LINKED ISSUE #431: Transition to Bootstrap for UI positioning
The current UI has a significant amount of CSS for handlign the layout of elements. Transitioning to using Bootstrap Grid will simplify the CSS as well as make the project more maintainable.

c.c.: @loneil @Gavinok

### PR DESCRIPTION
**Pull request by Gavinok**
This pr resolves #431

All that remains when it comes to CSS are classes or IDs accessed via javascript (should be resolved with #432) or custom overrides for bootstrap it's self. 

Updated look for desktop:

Updated look for mobile:

### CODE REVIEW

**Comment by Gavinok** [comment]
I will setup a meeting to discuss any changes to be made

**Comment by loneil** [comment]
One note from Kim, can we move the refresh icon to the left here
image

like it was originally
image
(but keeping the new opaqueness, that's a good improvement for readability)

"To the left please. That makes it seem more like a button and less like a status"

**Comment by loneil** [comment]
Also get a big blue outline in the pending state

image

**Comment by loneil** [comment]
Just a couple tweaks I noticed above that are worth focusing on but in general looking good.

I think there's some more grid changes and alignment tweaks for the "header-desc" info boxes we should do, however not worth looking at right now as they are working close enough as intended and we should go through a UX review to see if those will dramatically change anyways.

So (after tweaks above) worth merging and deploying to dev (to check on other devices) and then having UX review with Kim before going too much further

**Comment by Gavinok** [comment]
> Just a couple tweaks I noticed above that are worth focusing on but in general looking good.
> 
> I think there's some more grid changes and alignment tweaks for the "header-desc" info boxes we should do, however not worth looking at right now as they are working close enough as intended and we should go through a UX review to see if those will dramatically change anyways.
> 
> So (after tweaks above) worth merging and deploying to dev (to check on other devices) and then having UX review with Kim before going too much further

Just pushed these changes. Thanks for the feedback and testing. Should be good to go now.

**Review by loneil — APPROVED** [review]
Looks good for this milestone.

**Pull request merged**
