### PR TITLE
chore: Updating dependabot to support Vue, Python and Docker

### PR DESCRIPTION
**Pull request by rajpalc7**

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
@rajpalc7, it looks like you'll need to rebase your changes to resolve the conflicts.

**Comment by rajpalc7** [comment]
Thanks @WadeBarnes , rebasing looks good. Ready for review

**Comment by WadeBarnes** [comment]
No change here @rajpalc7, the diff still looks like this:
image

When it should look more like this:
image

**Comment by WadeBarnes** [comment]
See https://github.com/bcgov/vc-authn-oidc/pull/466/files

**Comment by rajpalc7** [comment]
Should be fixed now.

**Review by WadeBarnes — APPROVED** [review]
That's better.  Good job.

**Comment by rajpalc7** [comment]
Thank you Wade :)

**Pull request merged**
